version: "3.3"

services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=passwd
    ports:
      - 15672:15672
      - 5672:5672
  database:
    image: polyse/database
    environment:
      - LOG_LEVEL=debug
    ports:
      - 9000:9000
  listener:
    image: docker.pkg.github.com/polyse/web-scraper/listener
    restart: always
    environment:
      - RABBITMQ_URI=amqp://user:passwd@rabbitmq:5672
      - SERVER=http://database:9000
      - LOG_LEVEL=debug
    depends_on:
      - database
      - rabbitmq
  scrapper:
    image: docker.pkg.github.com/polyse/web-scraper/daemon
    restart: always
    environment:
      - RABBITMQ_URI=amqp://user:passwd@rabbitmq:5672
      - LOG_LEVEL=debug
      - LISTEN=0.0.0.0:7171
      - RATE_LIMIT=10
    ports:
      - 7171:7171
    depends_on:
      - listener
