version: "3.3"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=passwd
    ports:
      - 15672:15672
      - 5672:5672
  database:
    image: polyse/database
    container_name: database
    environment:
      - LOG_LEVEL=debug
    ports:
      - 9000:9000
  listener:
    image: docker.pkg.github.com/polyse/web-scraper/listener
    container_name: listener
    restart: always
    environment:
      - RABBITMQ_URI=amqp://user:passwd@rabbitmq:5672
      - SERVER=http://database:9000
      - LOG_LEVEL=debug
      - NUM_DOC=20
    depends_on:
      - database
      - rabbitmq
  scrapper:
    image: docker.pkg.github.com/polyse/web-scraper/daemon
    container_name: scrapper
    restart: always
    environment:
      - RABBITMQ_URI=amqp://user:passwd@rabbitmq:5672
      - LOG_LEVEL=debug
      - LISTEN=0.0.0.0:7171
      - RATE_LIMIT=10
      - REDIS_ADDR=redis:6379
    ports:
      - 7171:7171
    depends_on:
      - database
  front:
    image: docker.pkg.github.com/polyse/frontend-service/front
    container_name: front
    restart: always
    environment:
      - LOG_LEVEL=debug
      - LISTEN=0.0.0.0:9900
      - DB=http://database:9000
      - DBCollection=default
    ports:
      - 9900:9900
    depends_on:
      - database

