// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/polyse/web-scraper/internal/api"
	"github.com/polyse/web-scraper/internal/spider"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"os"
)

// Injectors from wire.go:

func initApp() (*api.API, func(), error) {
	mainConfig, err := newConfig()
	if err != nil {
		return nil, nil, err
	}
	spider, err := initSpider(mainConfig)
	if err != nil {
		return nil, nil, err
	}
	apiAPI, cleanup, err := initApi(mainConfig, spider)
	if err != nil {
		return nil, nil, err
	}
	return apiAPI, func() {
		cleanup()
	}, nil
}

// wire.go:

func initSpider(cfg *config) (*spider.Spider, error) {
	logLevel, err := zerolog.ParseLevel(cfg.LogLevel)
	if err != nil {
		log.Fatal().Err(err).Msgf("Can't parse loglevel")
	}
	zerolog.SetGlobalLevel(logLevel)
	log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})

	return spider.NewSpider()
}

func initApi(cfg *config, mod *spider.Spider) (*api.API, func(), error) {
	c, err := api.New(cfg.Listen, mod)
	return c, func() {
		c.Close()
	}, err
}
